"%dev":
  quarkus:
    datasource:
      db-kind: mysql
      username: root
      password: ""
      jdbc:
        url: jdbc:mysql://localhost:3306/activity_db
    hibernate-orm:
      database:
        generation: "drop-and-create"
    live-reload:
      instrumentation: true
  api:
    user-service:
      "client/mp-rest/url": "http://localhost:3000"
    document-service:
      "client/mp-rest/url": "http://localhost:4000"
  rabbit:
    username: "guest"
    password: "guest"
    virtualHost: "/"
    host: "localhost"
    port: 5672
    queue:
      consumer:
        document: "document-edit"
      producer:
        exchange: ""
        activity: "activity-update"
        document: "document-update"
"%test":
  quarkus:
    datasource:
      db-kind: h2
      jdbc:
        url: jdbc:h2:mem:default;DB_CLOSE_DELAY=-1
    hibernate-orm:
      dialect: org.hibernate.dialect.H2Dialect
      database:
        generation: drop-and-create
  api:
    user-service:
      "client/mp-rest/url": "http://localhost:3000"
    document-service:
      "client/mp-rest/url": "http://localhost:4000"
  rabbit:
    username: ""
    password: ""
    virtualHost: ""
    host: ""
    port: 8883
    queue:
      consumer:
        document: "document-edit"
      producer:
        exchange: ""
        activity: "activity-update"
        document: "document-update"