"%dev":
  greeting:
    message: HI

  quarkus:
    datasource:
      db-kind: mysql
      username: root
      password: 123
      jdbc:
        url: jdbc:mysql://localhost:3307/activity_db
    hibernate-orm:
      database:
        generation: drop-and-create
  api:
    user-service:
      "client/mp-rest/url": "http://localhost:8090"
      "client/mp-rest/scope": "javax.inject.Singleton"