quarkus:
  jacoco:
    excludes:
      - "dev/orion/entity/**/*"
      - "**/*dto/**/*"
      - "dev/orion/broker/**/*"
      - "dev/orion/repository/**/*"
      - "dev/orion/api/endpoint/body/**/*"
      - "dev/orion/commom/exception/**/*"
      - "dev/orion/util/setup/**/*"
    title: "Orion-services: Activity service"
  log:
    category:
      "org.apache.http":
        level:
          DEBUG

"%dev":
  quarkus:
    datasource:
      db-kind: mysql
      username: root
      password: ""
      jdbc:
        url: jdbc:mysql://localhost:3306/activity_db
    hibernate-orm:
      database:
#        generation: "drop-and-create"
    live-reload:
      instrumentation: true
  api:
    user-service:
      "client/mp-rest/url": "http://localhost:3000"
    document-service:
      "client/mp-rest/url": "http://localhost:4000"
    email-service:
      "client/mp-rest/url": "http://localhost:5000"
  rabbit:
    username: "activity"
    password: "activity"
    virtualHost: "/"
    host: "localhost"
    port: 5672
    queue:
      consumer:
        document: "document-edit"
      producer:
        exchange: ""
        activity: "activity-update"
        document: "document-update"
"%test":
  quarkus:
    datasource:
      db-kind: h2
      jdbc:
        url: jdbc:h2:mem:default;DB_CLOSE_DELAY=-1
    hibernate-orm:
      dialect: org.hibernate.dialect.H2Dialect
      database:
        generation: drop-and-create
  api:
    user-service:
      "client/mp-rest/url": "http://localhost:3000"
    document-service:
      "client/mp-rest/url": "http://localhost:4000"
  rabbit:
    queue:
      consumer:
        document: "document-edit"
      producer:
        exchange: ""
        activity: "activity-update"
        document: "document-update"