"%dev":
  quarkus:
    datasource:
      db-kind: mysql
      username: root
      password: 123
      jdbc:
        url: jdbc:mysql://localhost:3307/activity_db
    hibernate-orm:
      database:
        generation: drop-and-create
  api:
    user-service:
      "client/mp-rest/url": "http://localhost:8090"
"%test":
  quarkus:
    datasource:
      db-kind: h2
      jdbc:
        url: jdbc:h2:mem:default;DB_CLOSE_DELAY=-1
    hibernate-orm:
      dialect: org.hibernate.dialect.H2Dialect
      database:
        generation: drop-and-create
    api:
      user-service:
        "client/mp-rest/url": "http://localhost:8090"