version: '3'
services:
  mysql8:
    image: mysql:8
    container_name: mysql8
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: myDB
      MYSQL_USER: exampleUser
      MYSQL_PASSWORD: examplePassword
      MYSQL_ROOT_PASSWORD: 123
    ports:
      - 3307:3306
    volumes:
      - mysql8-storage:/var/lib/mysql

  rabbitMq:
    image: rabbitmq:3.9.2-management-alpine
    hostname: rabbit
    restart: unless-stopped
    ports:
      - "7010:15672"
      - "7000:5672"
    volumes:
      - rabbitmq-storage:/var/lib/rabbitmq
    environment:
      default_user: 'admin'
      DEFAULT_PASS: 'admin' 
volumes:
  mysql8-storage:
  rabbitmq-storage:

